//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosmoGraph.Desktop.ViewModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KosmoGraph.Desktop.ViewModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit entity {0}.
        /// </summary>
        public static string EditExistingEntityViewModelTitle {
            get {
                return ResourceManager.GetString("EditExistingEntityViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit facet {0}.
        /// </summary>
        public static string EditExistingTagViewModelTitle {
            get {
                return ResourceManager.GetString("EditExistingTagViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Entity.
        /// </summary>
        public static string EditNewEntityViewModelNameDefault {
            get {
                return ResourceManager.GetString("EditNewEntityViewModelNameDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Entity.
        /// </summary>
        public static string EditNewEntityViewModelTitle {
            get {
                return ResourceManager.GetString("EditNewEntityViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0}.
        /// </summary>
        public static string EditNewFacetNewPropertyNameDefault {
            get {
                return ResourceManager.GetString("EditNewFacetNewPropertyNameDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Facet.
        /// </summary>
        public static string EditNewFacetViewModelNameDefault {
            get {
                return ResourceManager.GetString("EditNewFacetViewModelNameDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Facet.
        /// </summary>
        public static string EditNewFacetViewModelTitle {
            get {
                return ResourceManager.GetString("EditNewFacetViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit new relationship from {0} to {1}.
        /// </summary>
        public static string EditNewRelationshipViewModelTitle {
            get {
                return ResourceManager.GetString("EditNewRelationshipViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit relationship from {0} to {1}.
        /// </summary>
        public static string EditRelationshipViewModelTitle {
            get {
                return ResourceManager.GetString("EditRelationshipViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity is name has to be unique.
        /// </summary>
        public static string ErrorEntityNameIsNotUnique {
            get {
                return ResourceManager.GetString("ErrorEntityNameIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name of Propery Definition isn&apos;t unique.
        /// </summary>
        public static string ErrorPropertyDefinitionNameIsNotUnique {
            get {
                return ResourceManager.GetString("ErrorPropertyDefinitionNameIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name has to be unique.
        /// </summary>
        public static string ErrorTagNameIsNotUnique {
            get {
                return ResourceManager.GetString("ErrorTagNameIsNotUnique", resourceCulture);
            }
        }
    }
}
